### ISSUE TITLE
Does not parse program without program statement

### ISSUE THREAD

**Issue by Beliavsky** [mwallerb/fsource#3]
For

```
print*,"hi"
end
```
I get

```
c:\python3\code>fsource parse try.f90
Traceback (most recent call last):
  File "c:\intelpython3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\intelpython3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\intelpython3\Scripts\fsource.exe\__main__.py", line 9, in <module>
  File "c:\intelpython3\lib\site-packages\fsource\__main__.py", line 187, in main
    cmd_parse(args)
  File "c:\intelpython3\lib\site-packages\fsource\__main__.py", line 167, in cmd_parse
    ast = parser.compilation_unit(tokens, fname)
  File "c:\intelpython3\lib\site-packages\fsource\parser.py", line 222, in rule_setup
    value = fn(tokens, *args)
  File "c:\intelpython3\lib\site-packages\fsource\parser.py", line 1851, in compilation_unit
    expect_cat(tokens, lexer.CAT_DOLLAR)
  File "c:\intelpython3\lib\site-packages\fsource\parser.py", line 122, in expect_cat
    raise NoMatch()
fsource.parser.NoMatch
```

fsource does work for

```
program main
print*,"hi"
end program main
```

**Comment by mwallerb** [comment]
Thanks for the bug report!

I did not know you could omit the `program` statement and still be valid Fortran!  This language is full of surprises ...

**Comment by apthorpe** [comment]
I saw this too; it's common to leave off `program` in legacy code. Not that it's good practice but it does save one punchcard :)

**Comment by apthorpe** [comment]
It looks like the last program unit to be checked for in `parser.py` is `function`. Changing

```python
def compilation_unit(tokens):
    with LockedIn(tokens, "expecting module or (sub-)program"):
        units = program_unit_sequence(tokens)
        expect_cat(tokens, lexer.CAT_DOLLAR)
    ...
```

to

```python
def compilation_unit(tokens):
    with LockedIn(tokens, "expecting module or (sub-)program"):
        units = program_unit_sequence(tokens)
        try:
            expect_cat(tokens, lexer.CAT_DOLLAR)
        except NoMatch:
            print("compilation_unit: check for implied PROGRAM statement")
            raise
    ...
```

is probably the least intrusive position where one might check if any program units had been found yet in the file. If any program unit has been detected, this is malformed code which should raise a parser error. If no program unit has been detected (i.e. top of file), a `PROGRAM` statement could be inferred. This probably entails tracking additional state during parsing ('beginning of file'?). It's better to trap and deal with it in `compilation_unit` than down in `function_decl` (if function detection was performed before subroutine detection, this check would need to move to the lowest check in the tree, `subroutine_decl` or below. That would change if new program units were added; less maintainable.)

To preserve performance and encourage good practice, one could add an `enable_legacy` option or only check fixed-format code. By F90, developers should use proper block format (`program <name>/end program <name>`); this exception should only be expected in older fixed-format code.

I'm stopping here; I don't want to suggest a fix before understanding if/how you want to track beginning-of-file context or state.
