### ISSUE TITLE
Scale factor without comma separator not recognized

### ISSUE THREAD

**Issue by apthorpe** [mwallerb/fsource#5]
The scale factor edit descriptor `P` may or may not be separated from other edit descriptors with a comma. The rules on this are not terribly clear (see Steve Lionel's comment on https://stackoverflow.com/questions/54945112/error-comma-required-after-p-descriptor-in-format-string). The case I typically see resembles `1PE12.4` where the comma is omitted.

I had some success replacing:

```python
    formattok = r"""\d*(?: [IBOZ] \d+ (?: \.\d+)?
                         | [FD]   \d+     \.\d+
                         | E[NS]? \d+     \.\d+  (?: E\d+)?
                         | G      \d+ (?: \.\d+  (?: E\d+)?)?
                         | L      \d+
                         | A      \d*
                         | [XP]
                         )(?=\s*[:/,)])"""
```

with

```python
    formattok = r"""\d*(?: [IBOZ] \d+ (?: \.\d+)?
                         | [FD]   \d+     \.\d+
                         | E[NS]? \d+     \.\d+  (?: E\d+)?
                         | G      \d+ (?: \.\d+  (?: E\d+)?)?
                         | L      \d+
                         | A      \d*
                         | X
                         )(?=\s*[:/,)])
                    |(?:-?\d+P)(?=\s*,?[\d:DEFG])"""
```
in `get_lexer_regex()` in `lexer.py` but I'm not convinced the lookahead assertion `(?=\s*,?[\d:DEFG])` is necessary or correct.

**Comment by mwallerb** [comment]
This looks good!  The lookahead assertion might not be necessary, however, its good to restrict these kinds of tokens as much as possible as they are "weird" (they can only occur in certain contexts.)

Can you make a PR?

**Comment by apthorpe** [comment]
I agree about the restrictions; I just feel more comfortable with peer review. Regexes can have subtle failure modes and I try to have a healthy skepticism of my code.
